parameters:
    # Adds a fallback DATABASE_URL if the env var is not set.
    # This allows you to run cache:warmup even if your
    # environment variables are not available yet.
    # You should not need to change this value.
    env(DATABASE_URL): ''

doctrine:
    dbal:
        # configure these for your database server
        driver: env(DATABASE_DRIVER)
        server_version: env(DATABASE_SERVER_VERSION)
        charset: utf8mb4

        url: '%env(resolve:DATABASE_URL)%'

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
            Project:
                is_bundle: false
                type: yml
                dir: '%kernel.project_dir%/src/Project/Resources/doctrine/mapping'
                prefix: 'App\Project\Domain'
                alias: App