nelmio_api_doc:
    documentation:
        info:
            title: Project Order
            description: Order Api with Symfony!
            version: 1.0.0

    areas: # to filter documented routes
        path_patterns:
            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc
