
orders.get:
    path: "/api/orders"
    methods: GET
    controller: App\Project\Http\Controller\OrderController:index

orders.get.by.id:
    path: "/api/orders/{id}"
    methods: GET
    controller: App\Project\Http\Controller\OrderController:order

orders.update.by.id:
    path: "/api/orders/{id}"
    methods: PUT
    controller: App\Project\Http\Controller\OrderController:update